/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as BloodGroupRouteImport } from './routes/blood-group'
import { Route as CoreRouteImport } from './routes/core'
import { Route as HomeVisitsRouteImport } from './routes/home-visits'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as LabsRouteImport } from './routes/labs'
import { Route as PayRouteImport } from './routes/pay'
import { Route as RxRouteImport } from './routes/rx'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AssistantIndexRouteImport } from './routes/assistant.index'
import { Route as AssistantThreadIdRouteImport } from './routes/assistant.$threadId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const BloodGroupRoute = BloodGroupRouteImport.update({
  id: '/blood-group',
  path: '/blood-group',
  getParentRoute: () => rootRouteImport,
} as any)
const CoreRoute = CoreRouteImport.update({
  id: '/core',
  path: '/core',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeVisitsRoute = HomeVisitsRouteImport.update({
  id: '/home-visits',
  path: '/home-visits',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const LabsRoute = LabsRouteImport.update({
  id: '/labs',
  path: '/labs',
  getParentRoute: () => rootRouteImport,
} as any)
const PayRoute = PayRouteImport.update({
  id: '/pay',
  path: '/pay',
  getParentRoute: () => rootRouteImport,
} as any)
const RxRoute = RxRouteImport.update({
  id: '/rx',
  path: '/rx',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantIndexRoute = AssistantIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AssistantRoute,
} as any)
const AssistantThreadIdRoute = AssistantThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => AssistantRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRouteWithChildren
  '/blood-group': typeof BloodGroupRoute
  '/core': typeof CoreRoute
  '/home-visits': typeof HomeVisitsRoute
  '/insights': typeof InsightsRoute
  '/labs': typeof LabsRoute
  '/pay': typeof PayRoute
  '/rx': typeof RxRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/assistant/$threadId': typeof AssistantThreadIdRoute
  '/assistant/': typeof AssistantIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blood-group': typeof BloodGroupRoute
  '/core': typeof CoreRoute
  '/home-visits': typeof HomeVisitsRoute
  '/insights': typeof InsightsRoute
  '/labs': typeof LabsRoute
  '/pay': typeof PayRoute
  '/rx': typeof RxRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/assistant/$threadId': typeof AssistantThreadIdRoute
  '/assistant': typeof AssistantIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRouteWithChildren
  '/blood-group': typeof BloodGroupRoute
  '/core': typeof CoreRoute
  '/home-visits': typeof HomeVisitsRoute
  '/insights': typeof InsightsRoute
  '/labs': typeof LabsRoute
  '/pay': typeof PayRoute
  '/rx': typeof RxRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/assistant/$threadId': typeof AssistantThreadIdRoute
  '/assistant/': typeof AssistantIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assistant'
    | '/blood-group'
    | '/core'
    | '/home-visits'
    | '/insights'
    | '/labs'
    | '/pay'
    | '/rx'
    | '/signin'
    | '/signup'
    | '/assistant/$threadId'
    | '/assistant/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blood-group'
    | '/core'
    | '/home-visits'
    | '/insights'
    | '/labs'
    | '/pay'
    | '/rx'
    | '/signin'
    | '/signup'
    | '/assistant/$threadId'
    | '/assistant'
  id:
    | '__root__'
    | '/'
    | '/assistant'
    | '/blood-group'
    | '/core'
    | '/home-visits'
    | '/insights'
    | '/labs'
    | '/pay'
    | '/rx'
    | '/signin'
    | '/signup'
    | '/assistant/$threadId'
    | '/assistant/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssistantRoute: typeof AssistantRouteWithChildren
  BloodGroupRoute: typeof BloodGroupRoute
  CoreRoute: typeof CoreRoute
  HomeVisitsRoute: typeof HomeVisitsRoute
  InsightsRoute: typeof InsightsRoute
  LabsRoute: typeof LabsRoute
  PayRoute: typeof PayRoute
  RxRoute: typeof RxRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blood-group': {
      id: '/blood-group'
      path: '/blood-group'
      fullPath: '/blood-group'
      preLoaderRoute: typeof BloodGroupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/core': {
      id: '/core'
      path: '/core'
      fullPath: '/core'
      preLoaderRoute: typeof CoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home-visits': {
      id: '/home-visits'
      path: '/home-visits'
      fullPath: '/home-visits'
      preLoaderRoute: typeof HomeVisitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labs': {
      id: '/labs'
      path: '/labs'
      fullPath: '/labs'
      preLoaderRoute: typeof LabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay': {
      id: '/pay'
      path: '/pay'
      fullPath: '/pay'
      preLoaderRoute: typeof PayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rx': {
      id: '/rx'
      path: '/rx'
      fullPath: '/rx'
      preLoaderRoute: typeof RxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant/': {
      id: '/assistant/'
      path: '/'
      fullPath: '/assistant/'
      preLoaderRoute: typeof AssistantIndexRouteImport
      parentRoute: typeof AssistantRoute
    }
    '/assistant/$threadId': {
      id: '/assistant/$threadId'
      path: '/$threadId'
      fullPath: '/assistant/$threadId'
      preLoaderRoute: typeof AssistantThreadIdRouteImport
      parentRoute: typeof AssistantRoute
    }
  }
}

interface AssistantRouteChildren {
  AssistantThreadIdRoute: typeof AssistantThreadIdRoute
  AssistantIndexRoute: typeof AssistantIndexRoute
}

const AssistantRouteChildren: AssistantRouteChildren = {
  AssistantThreadIdRoute: AssistantThreadIdRoute,
  AssistantIndexRoute: AssistantIndexRoute,
}

const AssistantRouteWithChildren = AssistantRoute._addFileChildren(
  AssistantRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssistantRoute: AssistantRouteWithChildren,
  BloodGroupRoute: BloodGroupRoute,
  CoreRoute: CoreRoute,
  HomeVisitsRoute: HomeVisitsRoute,
  InsightsRoute: InsightsRoute,
  LabsRoute: LabsRoute,
  PayRoute: PayRoute,
  RxRoute: RxRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
